# Day1 - 2023-09-04

### Scala? Vector? Tensor?
- Scala [x]
- Vector [x, y]
- Tensor [x, y, ...z]

In [ ]:
from torch import tensor

ex = tensor([[1, 2], [3, 4]])

print(ex)

In [1]:
import torch

print(torch.cuda.is_available())  # if False, cuda is not ready.
ex = torch.tensor([[1, 2], [3, 4]], device='cuda:0')

res = ex.to('cpu').numpy()

print(res)

False


AssertionError: Torch not compiled with CUDA enabled

In [38]:
import torch

a = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=torch.int8)
b = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=torch.int8)

c = a + b  # same indexes add together

print(c.shape)
print(c.view(8, 1))
print(c.view(1, 8))

torch.Size([2, 4])
tensor([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12],
        [14],
        [16]], dtype=torch.int8)
tensor([[ 2,  4,  6,  8, 10, 12, 14, 16]], dtype=torch.int8)


In [37]:
import pandas as pd
import torch

data = pd.read_csv("../data/test.csv")

scores = torch.from_numpy(data.values).unsqueeze(dim=1).int()

# names are not included because they are not numbers.
print("\t".join((data.keys())))
print(scores)

name	math	kor	sci
tensor([[[30, 40, 50,  6]],

        [[42, 43, 51, 41]],

        [[24, 57, 86, 42]],

        [[65, 32, 74, 21]]], dtype=torch.int32)


In [56]:
import pandas as pd
import torch

from torch.utils.data import Dataset, DataLoader


class CustomDataset(Dataset):
    def __init__(self, csv_file: str):
        self.label = pd.read_csv(csv_file)

    def __len__(self):
        return len(self.label)

    def __getitem__(self, idx):
        sample = torch.tensor(self.label.iloc[idx, 0:3]).int()
        label = torch.tensor(self.label.iloc[idx, 3]).int()
        return sample, label


tensor_dataset = CustomDataset("../data/test.csv")

dataset = DataLoader(tensor_dataset, batch_size=4, shuffle=True)

for i, data in enumerate(dataset, 0):
    print(i, data[0])

0 tensor([[24, 57, 86],
        [42, 43, 51],
        [30, 40, 50],
        [65, 32, 74]], dtype=torch.int32)


C:\Users\PleahMaCaka\AppData\Local\Temp\ipykernel_22436\3125166769.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sample = torch.tensor(self.label.iloc[idx, 0:3]).int()


In [57]:
import torchvision.transforms as transforms

from torchvision.datasets import MNIST

mnist_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (1.0,))
])

data_root = "../data/"
train_data = MNIST(root=data_root, train=True, download=True, transform=mnist_transform)
valid_data = MNIST(root=data_root, train=False, download=True, transform=mnist_transform)
test_data = MNIST(root=data_root, train=False, download=True, transform=mnist_transform)



Using downloaded and verified file: ../data/MNIST\raw\train-images-idx3-ubyte.gz
Extracting ../data/MNIST\raw\train-images-idx3-ubyte.gz to ../data/MNIST\raw

Using downloaded and verified file: ../data/MNIST\raw\train-labels-idx1-ubyte.gz
Extracting ../data/MNIST\raw\train-labels-idx1-ubyte.gz to ../data/MNIST\raw

Using downloaded and verified file: ../data/MNIST\raw\t10k-images-idx3-ubyte.gz
Extracting ../data/MNIST\raw\t10k-images-idx3-ubyte.gz to ../data/MNIST\raw



100.0%

Extracting ../data/MNIST\raw\t10k-labels-idx1-ubyte.gz to ../data/MNIST\raw
